
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    table: flyway_history_purchase_service
    baselineOnMigrate: true
  application:
    name: PAYMENT-SERVICE
#  config:
#    import: configserver:http://localhost:9296