server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/book/**
          filters:
            - name: CircuitBreaker
              args:
                name: BOOK-SERVICE
                fallbackUri: forward:/bookServiceFallback
        - id: RENTAL-SERVICE
          uri: lb://RENTAL-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: RENTAL-SERVICE
                fallbackUri: forward:/rentalServiceFallback