server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/library/**
          filters:
            - name: CircuitBreaker
              args:
                name: BOOK-SERVICE
                fallbackUri: forward:/bookServiceFallback
        - id: RENTAL-SERVICE
          uri: lb://RENTAL-SERVICE
          predicates:
            - Path=/rental/**
          filters:
            - name: CircuitBreaker
              args:
                name: RENTAL-SERVICE
                fallbackUri: forward:/rentalServiceFallback
        - id: OPINION-SERVICE
          uri: lb://OPINION-SERVICE
          predicates:
            - Path=/opinion/**
          filters:
            - name: CircuitBreaker
              args:
                name: OPINION-SERVICE
                fallbackUri: forward:/opinionServiceFallback
        - id: KAFKA-SERVICE
          uri: lb://KAFKA-SERVICE
          predicates:
            - Path=/emailSender/**
          filters:
            - name: CircuitBreaker
              args:
                name: KAFKA-SERVICE
                fallbackUri: forward:/kafkaServiceFallback