server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    table: flyway_history_book_service
    baseline: baselineOnMigrate
    baselineOnMigrate: true
  application:
    name: BOOK-SERVICE
  config:
    import: configserver:http://localhost:9296

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


