INSERT INTO book (name, author, quantity, publication_date)
VALUES
    ('Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 5, 1997),
    ('The Lord of the Rings: The Fellowship of the Ring', 'J.R.R. Tolkien', 8, 1954),
    ('The Book Thief', 'Markus Zusak', 3, 2005),
    ('1984', 'George Orwell', 7, 1949),
    ('It', 'Stephen King', 2, 1986),
    ('The Famished Road', 'Ben Okri', 10, 1991),
    ('Pride and Prejudice', 'Jane Austen', 1, 1813),
    ('The Master and Margarita', 'Mikhail Bulgakov', 6, 1966),
    ('The Alchemist', 'Paulo Coelho', 4, 1988),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 9, 1925),
    ('Children of Noisy Village', 'Astrid Lindgren', 5, 1947),
    ('The Shining', 'Stephen King', 8, 1977),
    ('Red Dragon', 'Thomas Harris', 3, 1981),
    ('Crime and Punishment', 'Fyodor Dostoevsky', 7, 1866),
    ('To Kill a Mockingbird', 'Harper Lee', 4, 1960),
    ('The Catcher in the Rye', 'J.D. Salinger', 9, 1951),
    ('Brave New World', 'Aldous Huxley', 6, 1932),
    ('The Hobbit', 'J.R.R. Tolkien', 2, 1937),
    ('The Da Vinci Code', 'Dan Brown', 5, 2003);
